[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps =
  fastled/FastLED
  bblanchon/ArduinoJson
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer

